apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: agent-config
rendezvousIP: 192.168.46.50
additionalNTPSources:
- 0.rhel.pool.ntp.org
- 1.rhel.pool.ntp.org
hosts:
- hostname: master0
  role: master
  interfaces:
  - name: eth0
    macAddress: '00:50:56:00:00:00'
  networkConfig:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.46.50
          prefix-length: 24
        enabled: true
    dns-resolver:
      config:
        server:
        # - 192.168.46.1
        - 8.8.8.8
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.46.1
        next-hop-interface: eth0
        metric: 150
- hostname: master1
  role: master
  interfaces:
  - name: eth0
    macAddress: '00:50:56:00:00:01'
  networkConfig:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.46.51
          prefix-length: 24
        enabled: true
    dns-resolver:
      config:
        server:
        # - 192.168.46.1
        - 8.8.8.8
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.46.1
        next-hop-interface: eth0
        metric: 150
- hostname: master2
  role: master
  interfaces:
  - name: eth0
    macAddress: '00:50:56:00:00:02'
  networkConfig:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.46.52
          prefix-length: 24
        enabled: true
    dns-resolver:
      config:
        server:
        # - 192.168.46.1
        - 8.8.8.8
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.46.1
        next-hop-interface: eth0
        metric: 150
- hostname: worker0
  role: worker
  interfaces:
  - name: eth0
    macAddress: '00:50:56:00:00:03'
  networkConfig:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.46.53
          prefix-length: 24
        enabled: true
    dns-resolver:
      config:
        server:
        # - 192.168.46.1
        - 8.8.8.8
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.46.1
        next-hop-interface: eth0
        metric: 150
- hostname: worker1
  role: worker
  interfaces:
  - name: eth0
    macAddress: '00:50:56:00:00:04'
  networkConfig:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.46.54
          prefix-length: 24
        enabled: true
    dns-resolver:
      config:
        server:
        # - 192.168.46.1
        - 8.8.8.8
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.46.1
        next-hop-interface: eth0
        metric: 150
- hostname: worker2
  role: worker
  interfaces:
  - name: eth0
    macAddress: '00:50:56:00:00:05'
  networkConfig:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.46.55
          prefix-length: 24
        enabled: true
    dns-resolver:
      config:
        server:
        # - 192.168.46.1
        - 8.8.8.8
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.46.1
        next-hop-interface: eth0
        metric: 150