apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
spec:
  llm:
    providers:
      - name: my-openai
        type: openai
        credentialsSecretRef:
          name: openai-credential
        url: https://api.openai.com/v1
        models:
          - name: gpt-5
  ols:
    defaultModel: gpt-5
    defaultProvider: my-openai
    introspectionEnabled: true
