apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: noobaa-pv-backing-store
  namespace: openshift-storage
  finalizers:
  - noobaa.io/finalizer
  labels:
    app: noobaa
spec:
  type: pv-pool
  pvPool:
    numVolumes: 1
    resources:
      requests:
        storage: 50Gi