---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system
    openshift.io/cluster-monitoring: "true"
    istio-discovery: enabled
    ossm3-discovery: enabled
  name: istio-system
