---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketchat-data-claim
  labels:
    app: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: kubevirt-csi-infra-default