apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tempo-observability
resources:
- namespace.yaml
- rbac-tempostack-traces-writer.yaml
- bucket-secret.yaml
- tempostack.yaml
- ui-plugin.yaml