---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-writer
rules:
  - apiGroups:
      - tempo.grafana.com
    # names must match `spec.tenants.authentication[].tenantName` names in the TempoStack CR
    # tenant name must be set in HTTP header X-Scope-OrgID, e.g. "X-Scope-OrgID: dev"
    resources:
      - dev
      - prod
    resourceNames:
      - traces
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-writer
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: opentelemetry-collector