apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: github
spec:
  provider:
    github:
      appID: ${GITHUB_APP_ID}
      auth:
        privateKey:
          name: github-app-secret
          namespace: eso
          key: key.pem
      installationID: ${GITHUB_APP_INSTALLATION_ID}
      organization: joshgav-org