apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gha-secret01
  namespace: eso
spec:
  secretStoreRef:
    name: github
    kind: ClusterSecretStore
  target:
    name: gha-secret01
  data:
  - secretKey: TEST_ESO_SECRET
    remoteRef:
      key: TEST_ESO_SECRET