apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway3-bookinfo
  namespace: bookinfo
spec:
  commonName: 'istio-ingressgateway3-bookinfo.apps.ipi.aws.joshgav.com'
  dnsNames:
    - 'istio-ingressgateway3.apps.ipi.aws.joshgav.com'
    - 'istio-ingressgateway3-bookinfo.apps.ipi.aws.joshgav.com'
  secretName: istio-ingressgateway3-bookinfo-keypair
  issuerRef:
    name: acme
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizationalUnits:
      - 'kubernetes'
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
    - signing
