apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  resources:
    api:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 512Mi
    mgr:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 512Mi
    mon:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 512Mi
    osd:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 512Mi
    mds:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 300m
        memory: 512Mi
  multiCloudGateway:
    endpoints:
      minCount: 2
      maxCount: 2
      resources:
        requests:
          cpu: 300m
        limits:
          cpu: 300m
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephToolbox: {}
  mirroring: {}
  nodeTopologies: {}
  storageDeviceSets:
    - config: {}
      resources: {}
      placement: {}
      name: ocs-deviceset-gp3-csi
      dataPVCTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Ti
          storageClassName: gp3-csi
          volumeMode: Block
        status: {}
      count: 1
      replica: 3
      portable: true
      preparePlacement: {}
  version: 4.11.0