apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scc-anyuid-access
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-anyuid-to-rocketchat-default
subjects:
- kind: ServiceAccount
  name: default
  namespace: rocketchat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scc-anyuid-access