---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: quay-operator
spec:
    name: quay-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: stable-3.13
    installPlanApproval: Automatic