apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  extraConfig:
    # allows admins to generate API keys
    accounts.admin: apiKey
  ha:
    enabled: false
  monitoring:
    enabled: true
  rbac:
    defaultPolicy: "role:admin"
    policy: |
      g, system:cluster-admins, role:admin
    scopes: "[groups]"
  server:
    route:
      enabled: true
  controller:
    appSync: 60s
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "500m"
        memory: 1Gi
  sso:
    provider: dex
    dex:
      openShiftOAuth: true