---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
spec:
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: release-2.13
  installPlanApproval: Automatic
#   config:
#     nodeSelector:
#       node-role.kubernetes.io/infra: ""
#     tolerations:
#     - key: node-role.kubernetes.io/infra
#       effect: NoSchedule
#       operator: Exists