apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: awssm
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets-operator
            name: awssm-secret
            key: access-key-id
          secretAccessKeySecretRef:
            namespace: external-secrets-operator
            name: awssm-secret
            key: secret-access-key