apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret01
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target:
    name: aws-secret01
  data:
  - secretKey: test-key
    remoteRef:
      key: aws-secret01
      property: test-key