# agent-config.yaml
apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: mno2
rendezvousIP: 192.168.136.10
additionalNTPSources:
- 0.rhel.pool.ntp.org
- 1.rhel.pool.ntp.org
hosts:
- hostname: master0
  role: master
  interfaces:
  - name: eno1
    macAddress: 52:54:01:ee:42:e0
- hostname: master1
  role: master
  interfaces:
  - name: eno1
    macAddress: 52:54:01:ee:42:e1
- hostname: master2
  role: master
  interfaces:
  - name: eno1
    macAddress: 52:54:01:ee:42:e2