# from https://access.redhat.com/solutions/6692341
# creates /etc/modprobe.d/kvm.conf with contents:
#   options kvm_intel nested=1
#   options kvm_amd nested=1
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 80-enable-nested-virt
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyBrdm1faW50ZWwgbmVzdGVkPTEKb3B0aW9ucyBrdm1fYW1kIG5lc3RlZD0xCg==
          verification: {}
        filesystem: root
        mode: 420
        path: /etc/modprobe.d/kvm.conf
  osImageURL: ""