kind: Secret
apiVersion: v1
metadata:
  name: vmware-credentials
  namespace: openshift-mtv
type: Opaque
stringData:
  insecureSkipVerify: 'true'
  password: ${VCENTER_PASSWORD}
  thumbprint: ${VCENTER_THUMBPRINT}
  url: ${VCENTER_URL}
  user: ${VCENTER_USERNAME}
