apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  exporter:
    endpoint: 'http://cluster-opentelemetry-collector-headless.tracing-system.svc:4317'
  java:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: none