---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-db
  labels:
    app: rocketchat
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rocketchat-db
    spec:
      containers:
        - name: rocketchat-db
          image: docker.io/library/mongo:8
          command:
            - /bin/sh
            - -c
            - >
              mongod --bind_ip 0.0.0.0 --port 27017
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: rocketchat-data
              mountPath: /data/db
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mongosh --eval 'db.adminCommand("ping")'
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 2
            failureThreshold: 3
      volumes:
        - name: rocketchat-data
          persistentVolumeClaim:
            claimName: rocketchat-data-claim