---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: odf-operator
spec:
    name: odf-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    channel: stable-4.11
    installPlanApproval: Automatic