apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  version: default
  istio_namespace: istio-system
  deployment:
    cluster_wide_access: true
    pod_annotations:
      sidecar.istio.io/inject: "false"
  external_services:
    istio:
      istiod_deployment_name: istiod
      config_map_name: istio
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: true
      namespace_selector: true
      provider: tempo
      # use_grpc: true
      # grpc_port: 9095
      # internal_url: tempo-default-query-frontend.tempo-observability.svc.cluster.local:9095
      use_grpc: false
      internal_url: https://tempo-default-query-frontend.tempo-observability.svc.cluster.local:3200/
      external_url: https://tempo-default-gateway-tempo-observability.apps.cluster-tf9nd.tf9nd.sandbox2654.opentlc.com/api/traces/v1/dev
      auth:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        insecure_skip_verify: true
        type: bearer
        use_kiali_token: true
      tempo_config:
        url_format: "grafana"
        datasource_uid: "a8d2ef1c-d31c-4de5-a90b-e7bc5252cd00"
        org_id: "1"