apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  version: default
  istio_namespace: istio-system
  deployment:
    cluster_wide_access: true
    pod_annotations:
      sidecar.istio.io/inject: "false"
  external_services:
    # istio:
    #   istiod_deployment_name: istiod-main-v1-24-latest
    #   config_map_name: istio-main-v1-24-latest
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: true
      namespace_selector: true
      provider: tempo
      # use_grpc: true
      # grpc_port: 8090
      use_grpc: false
      internal_url: https://tempo-default-gateway.tempo-observability.svc.cluster.local:8080/api/traces/v1/dev/tempo
      external_url: https://tempo-default-gateway-tempo-observability.apps.ipi.aws.joshgav.com/api/traces/v1/dev/search
      auth:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        insecure_skip_verify: true
        type: bearer
        use_kiali_token: true
      tempo_config:
        url_format: "grafana"
        datasource_uid: "a8d2ef1c-d31c-4de5-a90b-e7bc5252cd00"
        org_id: "1"