apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: httpbin
resources:
- ../base
- 01-namespace.yaml
- 03b-machinenet-nncp.yaml
- 04-deployment.yaml
- 05a-istio-ingress-gateway-role.yaml
- 05b-istio-ingress-gateway-service.yaml
- 05c-istio-ingress-gateway-deployment.yaml
- 06-istio-gateway.yaml
- 07-istio-virtualservice.yaml
- 08-hpa.yaml
- 09-pdb.yaml
- 10-route.yaml
- 11-podmonitor.yaml